apiVersion: v1
kind: Pod
metadata:
  name: hello
  namespace: default
  # Change the namespace to your namespace
spec:
  containers:
  - name: hello
    image: nginx:1.21
    #what is the latest version of nginx? 
    # Visit https://hub.docker.com/_/nginx
    ports:
    - containerPort: 80
    resources:
      limits:
        cpu: 1000m
        memory: 500Mi           
      requests:
        cpu: 500m
        memory: 100Mi      