
apiVersion: v1
kind: Service
metadata:
  name: flask
  namespace: default
  labels:
    app: flask
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
      app: flask
  type: ClusterIP
  sessionAffinity: None
